# Generated by Django 3.1.2 on 2020-11-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=14)),
                ('summary', models.TextField(max_length=2000)),
                ('degree', models.CharField(max_length=80)),
                ('school', models.CharField(max_length=80)),
                ('university', models.CharField(blank=True, max_length=80)),
                ('previous_work', models.CharField(max_length=200)),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
    ]
